// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svqguemfjbuiigijtnfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2cWd1ZW1mamJ1aWlnaWp0bmZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDMxNTIsImV4cCI6MjA2MjExOTE1Mn0.hiEq03qBdYeU4WluGeoKIw5QahSqJDiolI3Zi8uWlJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);